In [12]:
# Programming challenge from 100 days of code
height = int(input("Enter your height in cm"))

if height > 120:
    print("You can ride")
    age = int(input("Please enter your age"))
    if age < 12:
        bill = 5
        print("Ticket is $5")
    elif age >= 18:
        bill = 12
        print("Ticket is $12")
    else:
        bill = 7
        print("Ticket is $7")
    photos = str(input("Do you want photos y/n?"))
    if photos == "y":
        bill += 3
        print(f"Your total is {bill}")
else:
    print("You gotta grow taller")

Enter your height in cm 122


You can ride


Please enter your age 11


Ticket is $5


Do you want photos y/n? n


In [18]:
!pip install numpy


     |████████████████████████████████| 17.3 MB 4.3 MB/s eta 0:00:01


In [23]:
# Importing numpy after installing in above step
import numpy as np
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 40]])

In [26]:
weights = ([0.3, 0.2, 0.5])

In [27]:
weights

[0.3, 0.2, 0.5]

In [28]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  40]])

In [29]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 59.9])

In [30]:
# another way to run above calculatio
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 59.9])